In [1]:
import pandas as pd

In [2]:
path = 'divida_ativa_uniao.csv'
df = pd.read_csv(path)
df

,CNAE Classe,Ano da Inscrição,Número de Inscrição,CPF/CNPJ do Devedor Detalhado,Nome do Devedor Detalhado,Endereço CEP,Endereço Logradouro,Endereço Bairro,Município do Devedor,UF do Devedor,Tipo da Situação da Inscrição,Tipo Inscrição,Tipo Regularidade da Inscrição,Todas Origens - Valor Consolidado da Inscrição
0,Atividades de organizações religiosas,2021,426861485,03.568.054/0001-46,IGREJA BATISTA EL-BETEL DE FORTALEZA,60762130,RUA DR. JOSE DUTRA,MONDUBIM,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"1.060,31"
1,Atividades de organizações religiosas,2021,175614490,10.483.076/0001-79,IGREJA EVANGELICA ATALAIA DO DEUS VIVO,60720000,AVENIDA GENERAL OSORIO DE PAIVA,PARANGABA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"726,24"
2,Atividades de organizações religiosas,2021,175614504,10.483.076/0001-79,IGREJA EVANGELICA ATALAIA DO DEUS VIVO,60720000,AVENIDA GENERAL OSORIO DE PAIVA,PARANGABA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"3.931,93"
3,Atividades de organizações religiosas,2021,175616868,11.963.958/0001-02,IGREJA CRISTA INTERNACIONAL NOVA VIDA,60440105,RUA RIO BRANCO,DEMOCRITO ROCHA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"757,71"
4,Atividades de organizações religiosas,2021,175616876,11.963.958/0001-02,IGREJA CRISTA INTERNACIONAL NOVA VIDA,60440105,RUA RIO BRANCO,DEMOCRITO ROCHA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"2.538,37"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,Atividades de organizações religiosas,2004,30 6 04 004041-92,07.210.925/0001-06,MITRA ARQUIDIOCESANA DE FORTALEZA,60060090,AVENIDA DOM MANUEL,CENTRO,FORTALEZA,CEARA,Benefício Fiscal,Não Previdenciário,Situação Regular,"52.798,35"
325,Atividades de organizações religiosas,2001,FGCE200100236,12.221.396/0001-86,ASSOCIACAO CENTRO DE APOIO A JUVENTU E CENTRO ...,60130120,RUA ISAC AMARAL,DIONISIO TORRES,FORTALEZA,CEARA,Em cobrança,Contribuições FGTS,Situação Irregular,"2.781,36"
326,Atividades de organizações religiosas,2000,351065628,07.472.632/0001-05,ESCOLA SAO RAFAEL 1 E 2 GRAUS,60015052,AVENIDA IMPERADOR,NaN,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"206.070,88"
327,Atividades de organizações religiosas,2000,351065644,07.472.632/0001-05,ESCOLA SAO RAFAEL 1 E 2 GRAUS,60015052,AVENIDA IMPERADOR,NaN,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"433.479,80"
328,Atividades de organizações religiosas,1996,316998044,07.264.138/0002-28,INSTITUTO DR ROCHA LIMA DE PROTECAO E ASSIST A...,60325001,AVENIDA BEZERRA MENEZES,SAO GERARDO,FORTALEZA,CEARA,Garantia,Previdenciário,Situação Regular,"177.346,38"

In [246]:
df.columns

Index(['CNAE Classe', 'Ano da Inscrição', 'Número de Inscrição',
       'CPF/CNPJ do Devedor Detalhado', 'Nome do Devedor Detalhado',
       'Endereço CEP', 'Endereço Logradouro', 'Endereço Bairro',
       'Município do Devedor', 'UF do Devedor',
       'Tipo da Situação da Inscrição', 'Tipo Inscrição',
       'Tipo Regularidade da Inscrição',
       'Todas Origens - Valor Consolidado da Inscrição', 'CNPJ_basico',
       'valor'],
      dtype='object')

In [247]:
df.shape

(329, 16)

In [49]:
df['valor'] = df['Todas Origens - Valor Consolidado da Inscrição'].apply(lambda x: x.replace('.','').replace(',','.')).astype(float)

In [255]:
df['Tipo Regularidade da Inscrição'].value_counts()

Situação Irregular    233
Situação Regular       96
Name: Tipo Regularidade da Inscrição, dtype: int64

In [234]:
df['Tipo da Situação da Inscrição'].value_counts()

Em cobrança         233
Benefício Fiscal     95
Garantia              1
Name: Tipo da Situação da Inscrição, dtype: int64

In [235]:
df['Tipo Inscrição'].value_counts()

Não Previdenciário            188
Previdenciário                136
Contribuições FGTS              3
Contribuições LC110 (FGTS)      2
Name: Tipo Inscrição, dtype: int64

In [92]:
df['CNPJ_basico'] = df['CPF/CNPJ do Devedor Detalhado'].apply(lambda x: x.replace('.','')[0:8]).astype('int64')

In [36]:
df['CNPJ_basico'].value_counts()

7210925     18
7320880     17
9255212     16
5601588     15
7294093     13
            ..
19649245     1
1151206      1
10365164     1
20485358     1
17197339     1
Name: CNPJ_basico, Length: 167, dtype: int64

In [37]:
df['CPF/CNPJ do Devedor Detalhado'].value_counts()

07.210.925/0001-06    18
07.320.880/0001-22    17
09.255.212/0001-94    16
05.601.588/0001-52    15
07.294.093/0001-53    13
                      ..
03.463.489/0001-26     1
02.406.590/0001-82     1
11.822.038/0001-66     1
21.186.965/0001-90     1
13.861.960/0001-98     1
Name: CPF/CNPJ do Devedor Detalhado, Length: 167, dtype: int64

In [256]:
df.loc[df.CNPJ_basico == '07210925']

Empty DataFrame
Columns: [CNAE Classe, Ano da Inscrição, Número de Inscrição, CPF/CNPJ do Devedor Detalhado, Nome do Devedor Detalhado, Endereço CEP, Endereço Logradouro, Endereço Bairro, Município do Devedor, UF do Devedor, Tipo da Situação da Inscrição, Tipo Inscrição, Tipo Regularidade da Inscrição, Todas Origens - Valor Consolidado da Inscrição, CNPJ_basico, valor]
Index: []

In [261]:
df.loc[df['Ano da Inscrição'] == 1996]

,CNAE Classe,Ano da Inscrição,Número de Inscrição,CPF/CNPJ do Devedor Detalhado,Nome do Devedor Detalhado,Endereço CEP,Endereço Logradouro,Endereço Bairro,Município do Devedor,UF do Devedor,Tipo da Situação da Inscrição,Tipo Inscrição,Tipo Regularidade da Inscrição,Todas Origens - Valor Consolidado da Inscrição,CNPJ_basico,valor
328,Atividades de organizações religiosas,1996,316998044,07.264.138/0002-28,INSTITUTO DR ROCHA LIMA DE PROTECAO E ASSIST A...,60325001,AVENIDA BEZERRA MENEZES,SAO GERARDO,FORTALEZA,CEARA,Garantia,Previdenciário,Situação Regular,"177.346,38",7264138,177346.38

In [203]:
grupo_cnpj = df.groupby('CNPJ_basico')['valor'].sum().reset_index()
grupo_cnpj

     CNPJ_basico     valor
0         204897   1141.91
1         357571   1788.76
2         379432   1135.42
3         900289   4970.33
4         948286  29040.85
..           ...       ...
162     35076272  18059.84
163     41302647   5058.51
164     41655911   2539.32
165     63476212   2408.28
166     63500268   4770.04

[167 rows x 2 columns]

In [198]:
grupo_cnpj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CNPJ_basico  167 non-null    int64
 1   valor        167 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 2.7 KB

In [204]:
def getDividas(cnpj):
    
    dividas = df.loc[df.CNPJ_basico == cnpj]
    
    nDividas = dividas.shape[0]
    nome = dividas.iloc[0]['Nome do Devedor Detalhado']       
    
    return [nome, nDividas, dividas.filter(['Ano da Inscrição', 'Número de Inscrição','Tipo da Situação da Inscrição', 'Tipo Inscrição',
       'Tipo Regularidade da Inscrição','valor']).to_dict('records')]

In [200]:
# grupo_cnpj['Dividas'] = grupo_cnpj['CNPJ_basico'].apply(lambda x: getDividas(x))

In [248]:
grupo_cnpj['Nome'] = grupo_cnpj['CNPJ_basico'].apply(lambda x: getDividas(x)[0])
grupo_cnpj['nDividas'] = grupo_cnpj['CNPJ_basico'].apply(lambda x: getDividas(x)[1])
grupo_cnpj['Dividas'] = grupo_cnpj['CNPJ_basico'].apply(lambda x: getDividas(x)[2])

grupo_cnpj['valor'] = round(grupo_cnpj['valor'],2)

In [249]:
grupo_cnpj

,CNPJ_basico,valor,Nome,nDividas,Dividas
0,204897,1141.91,IGREJA EVANGELICA CONGREGACIONAL DO CONJUNTO C...,1,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
1,357571,1788.76,ASSOCIACAO JESUS E MARIA,1,"[{'Ano da Inscrição': 2020, 'Número de Inscriç..."
2,379432,1135.42,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,1,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
3,900289,4970.33,IGREJA BATISTA ESPERANCA,3,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
4,948286,29040.85,COMUNIDADE EVANGELICA TEMPLO DOS PRINCIPES,2,"[{'Ano da Inscrição': 2018, 'Número de Inscriç..."
...,...,...,...,...,...
162,35076272,18059.84,IGREJA BATISTA EM EDSON QUEIROZ- IBEQ,4,"[{'Ano da Inscrição': 2020, 'Número de Inscriç..."
163,41302647,5058.51,IGREJA DE CRISTO NO PARQUE ARAXA,1,"[{'Ano da Inscrição': 2019, 'Número de Inscriç..."
164,41655911,2539.32,IGREJA EVANGELICA ASSEMBLEIA DE DEUS MIN DE MA...,1,"[{'Ano da Inscrição': 2019, 'Número de Inscriç..."
165,63476212,2408.28,AUGUSTA E RESP LOJA SIMBOLICA VIANA DE CARVALH...,2,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
166,63500268,4770.04,IGREJA CRISTA EVANGELICA MONTE SINAI,1,"[{'Ano da Inscrição': 2020, 'Número de Inscriç..."

In [250]:
grupo_cnpj['valor'].sum()

7962114.370000001

In [251]:
grupo_cnpj['nDividas'].sum()

329

In [253]:
dez_mais = grupo_cnpj.sort_values(by='valor', ascending = False).head(10)
dez_mais.to_csv('dez_mais_divida_ativa.csv', index=False)
dez_mais

,CNPJ_basico,valor,Nome,nDividas,Dividas
54,7320880,1992598.09,COLEGIO SAO VICENTE,17,"[{'Ano da Inscrição': 2012, 'Número de Inscriç..."
55,7472632,1612068.94,ESCOLA SAO RAFAEL 1 E 2 GRAUS,3,"[{'Ano da Inscrição': 2006, 'Número de Inscriç..."
23,4745591,819957.45,COMUNIDADE CRISTA VIDEIRA,13,"[{'Ano da Inscrição': 2019, 'Número de Inscriç..."
50,7210925,733017.37,MITRA ARQUIDIOCESANA DE FORTALEZA,18,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
75,9255212,593112.71,IGREJA COMUNIDADE CRISTA LOGOS,16,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
32,5601588,245792.15,CONGREGACAO PENIEL DE FORTALEZA,15,"[{'Ano da Inscrição': 2019, 'Número de Inscriç..."
53,7294093,242942.82,CONSELHO PAROQUIAL NOSSA SENHORA DE FATIMA,13,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
64,8181827,180497.88,IGREJA NOVA CRIACAO,8,"[{'Ano da Inscrição': 2021, 'Número de Inscriç..."
52,7264138,177346.38,INSTITUTO DR ROCHA LIMA DE PROTECAO E ASSIST A...,1,"[{'Ano da Inscrição': 1996, 'Número de Inscriç..."
29,5109490,135391.82,CONVENCAO DE MINISTROS DAS ASSEMBLEIAS DE DEUS...,1,"[{'Ano da Inscrição': 2009, 'Número de Inscriç..."

In [254]:
df.loc[df.CNPJ_basico == 7320880]

,CNAE Classe,Ano da Inscrição,Número de Inscrição,CPF/CNPJ do Devedor Detalhado,Nome do Devedor Detalhado,Endereço CEP,Endereço Logradouro,Endereço Bairro,Município do Devedor,UF do Devedor,Tipo da Situação da Inscrição,Tipo Inscrição,Tipo Regularidade da Inscrição,Todas Origens - Valor Consolidado da Inscrição,CNPJ_basico,valor
295,Atividades de organizações religiosas,2012,402722752,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"125.988,97",7320880,125988.97
298,Atividades de organizações religiosas,2011,390145807,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"417.369,36",7320880,417369.36
299,Atividades de organizações religiosas,2011,390145815,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"35.369,69",7320880,35369.69
300,Atividades de organizações religiosas,2011,394884329,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"20.474,96",7320880,20474.96
301,Atividades de organizações religiosas,2011,397903944,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"187.067,30",7320880,187067.30
302,Atividades de organizações religiosas,2011,397903952,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"4.796,50",7320880,4796.50
303,Atividades de organizações religiosas,2010,368698718,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"65.926,82",7320880,65926.82
304,Atividades de organizações religiosas,2010,368698726,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"223.721,99",7320880,223721.99
305,Atividades de organizações religiosas,2010,603641644,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"142.608,35",7320880,142608.35
309,Atividades de organizações religiosas,2009,363687262,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"2.659,36",7320880,2659.36
310,Atividades de organizações religiosas,2009,363687270,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"20.103,46",7320880,20103.46
311,Atividades de organizações religiosas,2009,363687289,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"32.225,11",7320880,32225.11
312,Atividades de organizações religiosas,2009,363687297,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"189.004,60",7320880,189004.60
313,Atividades de organizações religiosas,2009,364450509,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"64.672,55",7320880,64672.55
314,Atividades de organizações religiosas,2009,364450517,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"6.475,43",7320880,6475.43
318,Atividades de organizações religiosas,2008,361229631,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"83.141,18",7320880,83141.18
319,Atividades de organizações religiosas,2008,361229640,07.320.880/0001-22,COLEGIO SAO VICENTE,60352370,RUA SAO VICENTE DE PAULO,ANTONIO BEZERRA,FORTALEZA,CEARA,Em cobrança,Previdenciário,Situação Irregular,"370.992,46",7320880,370992.46

In [225]:
def getNumDividas(ano):
    return df.loc[df['Ano da Inscrição'] == ano].shape[0]

In [227]:
getNumDividas(2000)

2

In [244]:
grupo_ano = df.groupby('Ano da Inscrição')['valor'].sum().reset_index()

grupo_ano['valor'] = round(grupo_ano['valor'],2)
grupo_ano['Número de Dívidas'] = grupo_ano['Ano da Inscrição'].apply(lambda x: getNumDividas(x))
grupo_ano['Somatório Valor'] = round(grupo_ano['valor'].cumsum(),2)
grupo_ano['Somatório Número de Dívidas'] = grupo_ano['Número de Dívidas'].cumsum()
grupo_ano.to_csv('divida_por_ano.csv', index=False)

grupo_ano

,Ano da Inscrição,valor,Número de Dívidas,Somatório Valor,Somatório Número de Dívidas
0,1996,177346.38,1,177346.38,1
1,2000,639550.68,2,816897.06,3
2,2001,2781.36,1,819678.42,4
3,2004,52798.35,1,872476.77,5
4,2006,1124854.56,3,1997331.33,8
5,2007,44457.27,1,2041788.60,9
6,2008,502237.95,5,2544026.55,14
7,2009,497670.53,9,3041697.08,23
8,2010,432257.16,3,3473954.24,26
9,2011,686717.98,7,4160672.22,33
10,2012,200161.14,3,4360833.36,36
11,2013,7490.79,2,4368324.15,38
12,2014,109063.18,4,4477387.33,42
13,2015,365547.64,13,4842934.97,55
14,2016,612429.26,12,5455364.23,67
15,2018,1110652.48,42,6566016.71,109
16,2019,467553.06,70,7033569.77,179
17,2020,340595.34,67,7374165.11,246
18,2021,587949.26,83,7962114.37,329

# Cruzamento dos dados:

In [211]:
dfReceita = pd.read_csv('dfReceita_bairros.csv')

In [212]:
dfReceita.head(2)

,Unnamed: 0,CNPJ_basico,razao_social,Data início_atividade,Situação Cadastral,Data início_atividade.1,porte_da_empresa,End_comp,lat,lng,bairro_name,bairro_GID
0,0,41396805,IGREJA EVANGELICA BATISTA LIBERDADE,19920205.0,2.0,19920205.0,5.0,"RUA VINTE UM, 10, , JOSE WALTER, 170 60750...",-3.823826,-38.551302,Prefeito José Walter,89
1,1,41409178,IGREJA BATISTA BEREIANA,19920812.0,2.0,19920812.0,5.0,"RUA CAP VASCONCELOS, 347, , AEROLANDIA, 170 ...",-3.765210,-38.516996,Alto da Balança,93

In [214]:
merge = pd.merge(grupo_cnpj, dfReceita, on ='CNPJ_basico', how='outer', indicator=True)
merge

,CNPJ_basico,valor,Nome,nDividas,Dividas,Unnamed: 0,razao_social,Data início_atividade,Situação Cadastral,Data início_atividade.1,porte_da_empresa,End_comp,lat,lng,bairro_name,bairro_GID,_merge
0,204897,1141.91,IGREJA EVANGELICA CONGREGACIONAL DO CONJUNTO C...,1.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1604.0,IGREJA EVANGELICA CONGREGACIONAL DO CONJUNTO C...,19940919.0,2.0,19940919.0,5.0,"RUA DAS PEDRINHAS, 000069, , PARQUE GENIBAU, 1...",-3.761945,-38.600131,Genibaú,44,both
1,357571,1788.76,ASSOCIACAO JESUS E MARIA,1.0,"[{'Ano da Inscrição': 2020, 'Número de Inscriç...",1616.0,ASSOCIACAO JESUS E MARIA,19941220.0,2.0,19941220.0,5.0,"RUA MANOEL CASTELO BRANCO, 368, , MESSEJANA, 1...",-3.832085,-38.492096,Messejana,65,both
2,379432,1135.42,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,1.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1618.0,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,19950105.0,2.0,19950105.0,5.0,"RUA RIO PARAGUAI, 1015, , JARDIM IRACEMA, 170 ...",-3.727885,-38.584281,Jardim Iracema,21,both
3,379432,1135.42,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,1.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1619.0,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,20110606.0,2.0,20110606.0,5.0,"AVENIDA VINTE DE JANEIRO, 2148, , BARRA DO CEA...",-3.703727,-38.585152,Barra do Ceará,6,both
4,900289,4970.33,IGREJA BATISTA ESPERANCA,3.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1639.0,IGREJA BATISTA ESPERANCA,19951108.0,2.0,19951108.0,5.0,"RUA 107, 221, , CONJ ESPERANCA, 170 607503...",-3.801761,-38.546193,Parque Dois Irmãos,84,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2748,35327956,NaN,NaN,NaN,NaN,2746.0,IGREJA DO ESPIRITO SANTO DE DEUS,19910125.0,8.0,19910125.0,5.0,"AVENIDA JOAO PESSOA, SN, ANT USINA EVEREST, PA...",-3.768175,-38.560181,Parangaba,105,right_only
2749,35635207,NaN,NaN,NaN,NaN,2747.0,ASSOCIACAO CIVIL ESCOLA TEOLOGICA CHARLES SPUR...,20191114.0,2.0,20191114.0,5.0,"RUA ABILIO MARTINS, 1344, FUNDOS, AMADEU FURTA...",-3.742774,-38.564637,Amadeu Furtado,4,right_only
2750,36065100,NaN,NaN,NaN,NaN,2748.0,IGREJA E ASSEMBLEIA DE DEUS M L DO MUNDO EM J ...,19900904.0,8.0,19900904.0,5.0,"RUA E, 80, RESID.GUAJERU, MESSEJANA, 170 6...",-14.548710,-41.938715,Não identificado,Não identificado,right_only
2751,36065100,NaN,NaN,NaN,NaN,2749.0,IGREJA E ASSEMBLEIA DE DEUS M L DO MUNDO EM J ...,19900904.0,8.0,19900904.0,5.0,"RUA E, 80, RESID.GUAJERU, MESSEJANA, 170 6...",-3.832735,-38.494086,Messejana,65,right_only
2752,36480706,NaN,NaN,NaN,NaN,2750.0,ASSOCIACAO INSTITUTO ADOLPH FRITZ,20200218.0,2.0,20200218.0,5.0,"AVENIDA BARAO DE STUDART, 2360, 1305, JO...",-3.744155,-38.510038,Joaquim Távora,22,right_only

In [215]:
merge.loc[merge._merge == 'both']

,CNPJ_basico,valor,Nome,nDividas,Dividas,Unnamed: 0,razao_social,Data início_atividade,Situação Cadastral,Data início_atividade.1,porte_da_empresa,End_comp,lat,lng,bairro_name,bairro_GID,_merge
0,204897,1141.91,IGREJA EVANGELICA CONGREGACIONAL DO CONJUNTO C...,1.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1604.0,IGREJA EVANGELICA CONGREGACIONAL DO CONJUNTO C...,19940919.0,2.0,19940919.0,5.0,"RUA DAS PEDRINHAS, 000069, , PARQUE GENIBAU, 1...",-3.761945,-38.600131,Genibaú,44,both
1,357571,1788.76,ASSOCIACAO JESUS E MARIA,1.0,"[{'Ano da Inscrição': 2020, 'Número de Inscriç...",1616.0,ASSOCIACAO JESUS E MARIA,19941220.0,2.0,19941220.0,5.0,"RUA MANOEL CASTELO BRANCO, 368, , MESSEJANA, 1...",-3.832085,-38.492096,Messejana,65,both
2,379432,1135.42,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,1.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1618.0,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,19950105.0,2.0,19950105.0,5.0,"RUA RIO PARAGUAI, 1015, , JARDIM IRACEMA, 170 ...",-3.727885,-38.584281,Jardim Iracema,21,both
3,379432,1135.42,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,1.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1619.0,IGREJA EVANGELICA NOVA ALIANCA EM CRISTO,20110606.0,2.0,20110606.0,5.0,"AVENIDA VINTE DE JANEIRO, 2148, , BARRA DO CEA...",-3.703727,-38.585152,Barra do Ceará,6,both
4,900289,4970.33,IGREJA BATISTA ESPERANCA,3.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1639.0,IGREJA BATISTA ESPERANCA,19951108.0,2.0,19951108.0,5.0,"RUA 107, 221, , CONJ ESPERANCA, 170 607503...",-3.801761,-38.546193,Parque Dois Irmãos,84,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,35076272,18059.84,IGREJA BATISTA EM EDSON QUEIROZ- IBEQ,4.0,"[{'Ano da Inscrição': 2020, 'Número de Inscriç...",2743.0,IGREJA BATISTA EM EDSON QUEIROZ- IBEQ,19900524.0,2.0,19900524.0,5.0,"RUA DOUTOR CARLOS RIBEIRO PAMPLONA, 128, , EDS...",-3.774510,-38.480529,Edson Queiroz,57,both
283,41302647,5058.51,IGREJA DE CRISTO NO PARQUE ARAXA,1.0,"[{'Ano da Inscrição': 2019, 'Número de Inscriç...",1500.0,IGREJA DE CRISTO NO PARQUE ARAXA,19911022.0,2.0,19911022.0,5.0,"RUA FREI MARCELINO, 416, , PARQUE ARAXA, 170 ...",-3.740667,-38.550070,Rodolfo Teófilo,34,both
284,41655911,2539.32,IGREJA EVANGELICA ASSEMBLEIA DE DEUS MIN DE MA...,1.0,"[{'Ano da Inscrição': 2019, 'Número de Inscriç...",1530.0,IGREJA EVANGELICA ASSEMBLEIA DE DEUS MIN DE MA...,19930211.0,2.0,19930211.0,5.0,"AVENIDA DOS EXPEDICIONARIOS, 9997, , CONJ ITAP...",-3.779980,-38.545747,Serrinha,107,both
285,63476212,2408.28,AUGUSTA E RESP LOJA SIMBOLICA VIANA DE CARVALH...,2.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",1565.0,AUGUSTA E RESP LOJA SIMBOLICA VIANA DE CARVALH...,19910625.0,2.0,19910625.0,5.0,"RUA AMERICA, 100, , PLANALTO AYRTON SENNA, 170...",-3.822912,-38.577798,Planalto Ayrton Senna,115,both
286,63500268,4770.04,IGREJA CRISTA EVANGELICA MONTE SINAI,1.0,"[{'Ano da Inscrição': 2020, 'Número de Inscriç...",1566.0,IGREJA CRISTA EVANGELICA MONTE SINAI,19910917.0,4.0,19910917.0,5.0,"TRAVESSA SANTA CASSIANA, 62, , PARQUE SANTA MA...",-3.865717,-38.501330,Ancuri,50,both

In [218]:
merge.loc[merge._merge == 'left_only']

,CNPJ_basico,valor,Nome,nDividas,Dividas,Unnamed: 0,razao_social,Data início_atividade,Situação Cadastral,Data início_atividade.1,porte_da_empresa,End_comp,lat,lng,bairro_name,bairro_GID,_merge
66,6259742,14882.72,COMUNIDADE EVANGELICA TEMPLO DE ADORACAO,1.0,"[{'Ano da Inscrição': 2019, 'Número de Inscriç...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
190,9056991,15093.66,IGREJA CRISTA GILEADE DA GRANJA PORTUGAL,2.0,"[{'Ano da Inscrição': 2021, 'Número de Inscriç...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [219]:
merge.loc[merge._merge == 'right_only']

,CNPJ_basico,valor,Nome,nDividas,Dividas,Unnamed: 0,razao_social,Data início_atividade,Situação Cadastral,Data início_atividade.1,porte_da_empresa,End_comp,lat,lng,bairro_name,bairro_GID,_merge
287,41396805,NaN,NaN,NaN,NaN,0.0,IGREJA EVANGELICA BATISTA LIBERDADE,19920205.0,2.0,19920205.0,5.0,"RUA VINTE UM, 10, , JOSE WALTER, 170 60750...",-3.823826,-38.551302,Prefeito José Walter,89,right_only
288,41409178,NaN,NaN,NaN,NaN,1.0,IGREJA BATISTA BEREIANA,19920812.0,2.0,19920812.0,5.0,"RUA CAP VASCONCELOS, 347, , AEROLANDIA, 170 ...",-3.765210,-38.516996,Alto da Balança,93,right_only
289,41533342,NaN,NaN,NaN,NaN,2.0,IGREJA VIDA NOVA,20210211.0,2.0,20210211.0,5.0,"AVENIDA AUDIZIO PINHEIRO, 1082, , HENRIQUE JOR...",-3.760812,-38.590167,Henrique Jorge,45,right_only
290,41534812,NaN,NaN,NaN,NaN,3.0,IGREJA MINISTERIO SAL E LUZ FORTALEZA,20210218.0,2.0,20210218.0,5.0,"RUA CORONEL ALUISIO BORBA, 708, Q009, EN...",-3.778979,-38.490595,Engenheiro Luciano Cavalcante,58,right_only
291,41585977,NaN,NaN,NaN,NaN,4.0,ASSOCIACAO DOS PREGADORES DO REINO DE DEUS,20120621.0,2.0,20120621.0,5.0,"RUA OTAVIO PARANHOS, 385, , JARDIM IRACEMA, 17...",-3.721169,-38.585939,Jardim Iracema,21,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2748,35327956,NaN,NaN,NaN,NaN,2746.0,IGREJA DO ESPIRITO SANTO DE DEUS,19910125.0,8.0,19910125.0,5.0,"AVENIDA JOAO PESSOA, SN, ANT USINA EVEREST, PA...",-3.768175,-38.560181,Parangaba,105,right_only
2749,35635207,NaN,NaN,NaN,NaN,2747.0,ASSOCIACAO CIVIL ESCOLA TEOLOGICA CHARLES SPUR...,20191114.0,2.0,20191114.0,5.0,"RUA ABILIO MARTINS, 1344, FUNDOS, AMADEU FURTA...",-3.742774,-38.564637,Amadeu Furtado,4,right_only
2750,36065100,NaN,NaN,NaN,NaN,2748.0,IGREJA E ASSEMBLEIA DE DEUS M L DO MUNDO EM J ...,19900904.0,8.0,19900904.0,5.0,"RUA E, 80, RESID.GUAJERU, MESSEJANA, 170 6...",-14.548710,-41.938715,Não identificado,Não identificado,right_only
2751,36065100,NaN,NaN,NaN,NaN,2749.0,IGREJA E ASSEMBLEIA DE DEUS M L DO MUNDO EM J ...,19900904.0,8.0,19900904.0,5.0,"RUA E, 80, RESID.GUAJERU, MESSEJANA, 170 6...",-3.832735,-38.494086,Messejana,65,right_only
2752,36480706,NaN,NaN,NaN,NaN,2750.0,ASSOCIACAO INSTITUTO ADOLPH FRITZ,20200218.0,2.0,20200218.0,5.0,"AVENIDA BARAO DE STUDART, 2360, 1305, JO...",-3.744155,-38.510038,Joaquim Távora,22,right_only